In [ ]:
# 変数
a <- 5 # 変数に代入．宣言は必要ない．
b <- 8
a + b # 最後に実行したものが表示される．

# の後にスペース一つ開けて文字を書き始めるとコメント

In [3]:
c <- b - a 
c
# 変数の名前を書くと実行したことになって表示される
# (半分関数型言語のため，なんかの指揮を実行した時には必ず値が返る)

[1] 3

In [4]:
# print関数を使っても良い
# printを使うと，多次元配列の時何行目のprintなのかも表示してくれる
print(c)
# 上記はスカラ値で，1番目の要素のみなので,数字の前に[1]と出力される

[1] 3


In [5]:
# 他のプログラミング言語との大きな違いは，「.」が，
# 「オブジェクトインスタンスやクラスの中の要素」を表すのではなく，
# 普通の変数名に使える文字として使えること
y.a <- 3
y.b <- 4
print(y.a + y.b)
# 上記は「yというオブジェクトインスタンスの中のaオブジェクト」ではなく
# 「y.aという変数名」として扱われる
# 普通のプログラミング言語では，単語をつないだ変数名の場合，
# キャメルバック（ラクダの背中）形式:  sumOfThisArray のように，最初以外の単語の頭文字を大きくする
# アンダースコアで繋ぐ: sum_of_this_array
# の方法があるが，Rの場合はアンダースコアで繋ぐ形式を「.」に置き換えたもの，と言うことができる

[1] 7


In [6]:
# Rはpythonと同じくfor文のif文のブロックスコープを持たない

for (i in 1:10) {
  if (i == 1) {
    x <- i
  } else {
    x <- x + i
  }
}

# xという変数は，上のfor文のブロック内で初めて出てきた変数なので
# 普通の感覚から言うとfor文ブロックの実行が終わった後には破棄されるが，
print(x)
# ブロックの外からでもアクセスできる
# 関数ブロックスコープはある

# その代わりに，環境というオブジェクトのようなものがあり，そこに変数をくっつけることで，同じ名前の変数を増やすことができる

[1] 55


In [7]:
# インデックス
# 普通のプログラミング言語のインデックスは0から始まるが，Rは1からが原則
# 例えばfor文は
for (i in 1:10){
    print(i)
}

# となり，1から10までの値が出る
# 範囲指定でコロン「:」を使っていることに注意
# x:yという範囲指定の時 x以上，y以下の値が出る
# 10:1だと，10以下，1以上

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [8]:
# 配列 array
# 固定長配列でpythonでいう所のnumpy配列
# 1次元配列
# Rでは1次元配列はVector, ベクトルと呼ぶことが多い
# 例えば10要素を全部0.0で初期化したければ，
x <- array(0.0, dim=c(10))
print(x)
# と書く
# c(おそらくcolumnの略)関数に注意
# 1行目しかないので，printでは配列の前に[1]が表示される

 [1] 0 0 0 0 0 0 0 0 0 0


In [9]:
x <- array(1:10, dim=c(10))
print(x)
# 上記は，次元が1次元で10要素ある配列を作り，1~10まで順に入れていけ，という配列の作り方．

 [1]  1  2  3  4  5  6  7  8  9 10


In [10]:
# 前述のインデックスでわかる通り，配列のインデックスは1〜なので

x <- array(10:1, dim=c(10))
print(x[1])
# は配列xの「先頭の次」の要素ではなく，「先頭の要素」を指す

[1] 10


In [11]:
# 配列の連結
# c関数で結合できる
# c関数は非破壊的
x <- array(3:1, dim=c(3))
y <- array(6:4, dim=c(3))
w <- c(x, y)
print(w)

[1] 3 2 1 6 5 4


In [12]:
# 配列の要素の置き換え
# replace関数．やはり非破壊的
x <- array(3:1, dim=c(3))
y <- replace(x, 2, 4) # 配列xの2番目の要素を，4で置き換える
print(y)

[1] 3 4 1


In [13]:
# replaceはまとめて指定することができる
# 1番目と3番目の要素をそれぞれ5と7で置き換えるという処理の場合
x <- array(1:3, dim=c(3))
y <- replace(x, c(1, 3), c(5, 6))
print(y)

[1] 5 2 6


In [14]:
# 2次元配列
x <- array(1:6, dim=c(3, 2))
print(x)
# は3行2列の配列になる
# ここにきて，行と列があるので，print関数で出力される何番目の行か，何番目の列かがうまく機能するようになる

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [6]:
x <- matrix(1:6, nrow=3, ncol=2)
print(x)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [8]:
x <- matrix(1:6, nrow=3, ncol=2)
print(x)

print(x[2, ]) # 2行目を丸ごと
print(x[, 2]) # 2列目を丸ごと

print(x[1, 2]) # 1行目2列目の要素
print(x[c(1,2), 2]) # 1,2 行目2列目の要素

print(x[c(1,3), c(1:2)]) # 1,3行目の1から2列目の要素

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6
[1] 2 5
[1] 4 5 6
[1] 4
[1] 4 5
     [,1] [,2]
[1,]    1    4
[2,]    3    6


In [9]:
x <- matrix(1:6, nrow=3, ncol=2)
y <- matrix(7:12, nrow=3, ncol=2)

w = rbind(x, y) # 縦に結合
z = cbind(x, y) # 横に結合

print(w)
print(z)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6
[4,]    7   10
[5,]    8   11
[6,]    9   12
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


In [3]:
# C言語の配列やpythonのnumpy配列と同じく，最初に次元を定める必要があるので，
# insertなんかはない様子

In [5]:
# 配列list
# arrayは整数なら整数，実数なら実数というデータ型が決まっているが，
# listはなんでも入れられるため，複数のデータ型をまとめるデータ型という基準で作られている
# C言語の構造体に近い？
x <- list(8, array(1:4, dim=c(2, 2)), "文字列")
print(x)

[[1]]
[1] 8

[[2]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[3]]
[1] "文字列"



In [16]:
# 制御構造
# if文
# if文の中で普通に==，!=，>=，>などの通常の比較演算子を使うことができる．
# elseの前は改行してはいけないという規則がある
a <- 3
if (a == 1){
    print('aはいち！')
}else if (a < 2){
    print('aは2より小さい')
} else if(a < 2){
    print('aは3より小さい')
} else　{
    print('それ以外')
}

[1] "それ以外"


In [17]:
# if文の論理積と論理和はそれぞれ &&と||
a <- 2
b <- 4
(a < 3) && (a >1)  #TRUEが返る　BooleanはTRUEとFALSE

[1] TRUE

In [18]:
# switch文
# Rにはpythonと違いちゃんとswitch文がある
# ただし構文が非常に特殊
# 'マッチ文' = 処理式
# になる
a <- 3
switch(a,
       '1' = print('いち！'),
       '2' = print('に！'),
      '3'=print('さん！'),
       print('それ以外！')
      )
# 上記のように整数にマッチさせる時でもシングルクォーテーションかダブルクォーテーションで囲む必要がある

[1] "さん！"


In [1]:
# 関数の定義
#  funcという変数に，引数xを二乗して返す関数オブジェクトを生成して入れている
func <- function(x){ 
    ans <- x ** 2
    return(ans) # returnはキーワードではなく関数であることに注意
}

# 関数オブジェクトの呼び出し
a <- func(4)
print(a)

[1] 16
