In [52]:
# 要素を指定して生成
vec1 <- c(2, 4, 6, 8) 
vec2 <- c(1, 2, 1, 2)

# 各要素の演算
# ベクトルの各要素に2をかける
print(vec1 * 2)

# vec1の各要素からvec2の各要素で引く
print(vec1 - vec2)

# ベクトル同士の積(内積)
print(vec1 %*% vec2)

# ベクトル同士の外積(直積，テンソル積)
print(vec1 %o% vec2)

# sequence関数で生成
vec3 <- seq(1:5) # c(seq(開始:終了))
print(vec3)

vec3 <- seq(1, 10, length=5) # ,であることに注意．1から10まで要素数5の等差数列，つまり5段階で
print(vec3)

vec4 <- seq(1, 10, by=2) # ,であることに注意．1から10まで，2ずつ増やしながら．
print(vec4)

# repeat関数で生成
vec5 <- rep(1:2, times=5) # rep(繰り返し開始値:繰り返し終了値, time=繰り返し回数)
print(vec5)

vec6 <- rep(1:2, length=5) # rep(繰り返し開始値:繰り返し終了値, length=要素数) 要素数に達するまで繰り返される
print(vec6)

# 要素へのアクセス
print(vec1[3]) #インデックスが1~であることに注意

# 要素の追加
# 非破壊であることに注目
vec7 <- append(vec1, 9)
print(vec7)

[1]  4  8 12 16
[1] 1 2 5 6
     [,1]
[1,]   32
     [,1] [,2] [,3] [,4]
[1,]    2    4    2    4
[2,]    4    8    4    8
[3,]    6   12    6   12
[4,]    8   16    8   16
[1] 1 2 3 4 5
[1]  1.00  3.25  5.50  7.75 10.00
[1] 1 3 5 7 9
 [1] 1 2 1 2 1 2 1 2 1 2
[1] 1 2 1 2 1
[1] 6
[1] 2 4 6 8 9


In [50]:
p1 <- runif(10, min=-1.0, max=1.0) # -1から1までの一様分布を10個生成する runifはrandom uniformの略
print(vector(p1))
hist(p1) # ヒストグラムを描く

p2 <- rnorm(100, mean=5, sd=2) # 平均5，標準偏差2の分布に従う乱数を10個生成
hist(p2)

ERROR: Error in vector(p1): invalid 'mode' argument


In [30]:
# 要素の集計ビルトイン関数
print(sum(vec4)) # 合計
print(mean(vec4)) # 平均
print(median(vec4)) # 中央値
summary(vec4) # 全部表示

[1] 15
[1] 1.5
[1] 1.5


   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.0     1.0     1.5     1.5     2.0     2.0 

In [ ]:
print(max(vec3)) # 最大値
print(min(vec3)) # 最小値
print(which.max(vec3)) # 最大値のインデックス
print(which.min(vec3)) # 最小値のインデックス

print(unique(vec5)) # 重複する値を削除

In [5]:
# 2次元配列は前項のように2次元配列としても扱えるが，Rでは行列として扱うことが多い
# 要素を指定して生成
mat1 <- matrix(c(1, 2, 3, 4), 2, 2) # 2*2の行列
print(mat1)

# sequence関数で生成
mat2 <- matrix(c(seq(1:9)), 3, 3) # 3 * 3の行列
print(mat2)

# 

     [,1] [,2]
[1,]    1    3
[2,]    2    4
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
