In [1]:
# 国や自治体の機関が公開しているオープンデータは基本的にExcelからの書き出しであり
# 文字コードがSHIFT_JISなので，
# fileEncodingオプションに'Shift_JIS'を与えてやる
df <- read.csv('http://www.city.hachioji.tokyo.jp/contents/open/002/p005866_d/fil/nenreibetsu_jinkou_2506.csv', fileEncoding='Shift_JIS')
# data.frame形式で出力される
head(df)

対象年月 年齢 人口.合計 人口.男 人口.女
1 201306   0    3989      2041    1948   
2 201306   1    4249      2217    2032   
3 201306   2    4494      2318    2176   
4 201306   3    4719      2440    2279   
5 201306   4    4722      2382    2340   
6 201306   5    4762      2409    2353

In [8]:
# apply関数は，data.frame形式の行方向や列方向に対してなんらかの処理を行う関数．
# 行か列のベクトルが入り，処理をしたベクトルを返す
# apply(dataframe, 方向, 処理する内容を記述した関数オブジェクト)
# 方向は1なら行ごとのベクトルが入り，2なら列ごとベクトルが入って回る．

# まず処理する関数オブジェクトを作っておく
line.loop.func <- function(v){
    # ベクトルが引数になる
    # 行ごと，つまり年齢ごとに男性の人口 - 女性の人口を返す関数を作ると，こうなる
    return(v[4] - v[5])
}

# apply関数の行方向に対して，それぞれ上で作ったline.loop.funcという関数を食わせて，結果のベクトルを得る
sub_vec = apply(df, 1, line.loop.func)

# 折れ線グラフで描画する
age = length(df$'年齢')
plot(0:(age-1), sub_vec, type='l', lty=1, xlab='age', ylab='population')

In [27]:
# sapply関数
# リストやベクトルの全ての「要素」に対して適用する
# 行列に適用した場合は，全ての値に対して適用されるので注意

# 関数を定義しておいて
increase.func <- function(a){
    return(a+1)
}

# 偶数のベクトルを作り
vec1 <- seq(0, 10, by=2)
print(vec1)

# sapply関数を適用すると，奇数のベクトルができる
vec2 <- sapply(vec1, increase.func)
print(vec2)

# 同じく偶数の行列を作り
mat1 <- matrix(seq(0, 18, by=2), nrow=2, ncol=5)
print(mat1)
# spply関数を適用すると，奇数の行列ができる．入れたのが行列でも戻り値がベクトルになっていることに注意
mat2 <- sapply(mat1, increase.func)
print(mat2)

# なので受け取ったらこいつを行列にする
mat3 <- matrix(mat2, nrow=2, ncol=5)
print(mat3)

# lapply関数というのもあるが，これは必ず（ベクトルではなく）リストを返すのが特徴．
# listというのは構造体みたいなものだったね．

[1]  0  2  4  6  8 10
[1]  1  3  5  7  9 11
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    4    8   12   16
[2,]    2    6   10   14   18
 [1]  1  3  5  7  9 11 13 15 17 19
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    5    9   13   17
[2,]    3    7   11   15   19


In [21]:
# mapply関数は，apply関数の多変量版であり，複数のベクトルや行列を取ることができる
# 例えば以下のように男女の人口のベクトルが分かれている場合，

df.man = df$'人口.男'
df.woman = df$'人口.女'

# この2つのベクトルを行ごとに足した合計を出したいとする

# まず関数を定義
sum.loop.func <- function(a, b){
    # 合計を返す
    return(a + b)
}

# df.manとdf.womanに適用して結果を得る
sum.of.pop <- mapply(sum.loop.func, df.man, df.woman)

# 折れ線グラフで描画する
age = length(df$'年齢')
plot(0:(age-1), sum.of.pop, type='l', lty=1, xlab='age', ylab='population')

# 実はsum関数は既にあるので，以下のように書くだけでもいける
mapply(sum, df.man, df.woman)

[1] 3989 4249 4494 4719 4722 4762 4886 4831 4700 4889 5005 5125 5159 5307 5237
 [16] 5235 5275 5271 6762 7572 7610 7907 7235 6758 6579 6283 6236 6273 6292 6349
 [31] 6501 6438 6595 7093 7233 7519 7556 8179 8435 9133 9441 9329 9102 8899 8991
 [46] 8636 7961 7508 8163 7510 7291 6690 6676 6484 6418 6096 6121 6335 6515 6592
 [61] 7126 7505 8089 8942 9286 9824 8419 5527 6545 7945 7317 7396 6881 6298 5319
 [76] 5684 5274 5253 4623 4316 4074 3692 3389 2983 2698 2455 2186 1964 1633 1290
 [91] 1124  949  724  613  431  344  296  210  138  115   66   48   29    6   12
[106]    7    3    1    0    0    0    0    0    0    0    0    0    0    0    0
[121]    0

In [29]:
mat1 <- array(seq(1, 9), dim=c(3, 3))
print(mat1)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
